export const mockIngredients = [
  { name: 'Cà chua', icon: '🍅', confidence: 92 },
  { name: 'Hành tây', icon: '🧅', confidence: 88 },
  { name: 'Tỏi', icon: '🧄', confidence: 85 },
  { name: 'Ớt', icon: '🌶️', confidence: 80 },
  { name: 'Chanh', icon: '🍋', confidence: 75 },
]

export const mockRecipes = [
  {
    id: 1,
    name: 'Vietnamese Tomato Soup',
    emoji: '🍜',
    time: '20 min',
    difficulty: 'Easy',
    servings: 4,
    rating: 5,
    matchLevel: 'High match',
    ingredients: [
      { name: 'Cà chua', amount: '500g' },
      { name: 'Hành tây', amount: '200g' },
      { name: 'Tỏi', amount: '3 cloves' },
      { name: 'Nước cốt cà chua', amount: '200ml' },
      { name: 'Hành lá', amount: 'to taste' },
    ],
    instructions: [
      'Cắt cà chua và hành tây thành miếng nhỏ',
      'Phi thơm tỏi và hành tây trong dầu olive',
      'Thêm cà chua và nước cốt, nấu 10 phút',
      'Nêm gia vị và thêm hành lá',
      'Trang trí với rau mùi và phục vụ nóng',
    ],
  },
  {
    id: 2,
    name: 'Spicy Tomato Pasta',
    emoji: '🍝',
    time: '25 min',
    difficulty: 'Easy',
    servings: 2,
    rating: 4,
    matchLevel: 'High match',
    ingredients: [
      { name: 'Cà chua', amount: '400g' },
      { name: 'Tỏi', amount: '4 cloves' },
      { name: 'Ớt', amount: '1-2 pieces' },
      { name: 'Pasta', amount: '300g' },
      { name: 'Dầu olive', amount: '3 tbsp' },
    ],
    instructions: [
      'Luộc pasta theo hướng dẫn bao',
      'Phi thơm tỏi và ớt trong dầu olive',
      'Thêm cà chua cắt nhỏ, nấu 15 phút',
      'Trộn pasta với sốt',
      'Thêm phô mai Parmesan và phục vụ',
    ],
  },
  {
    id: 3,
    name: 'Vegetable Stir Fry',
    emoji: '🥘',
    time: '15 min',
    difficulty: 'Easy',
    servings: 3,
    rating: 4,
    matchLevel: 'Medium match',
    ingredients: [
      { name: 'Hành tây', amount: '200g' },
      { name: 'Tỏi', amount: '2 cloves' },
      { name: 'Ớt', amount: '1 piece' },
      { name: 'Dầu thực vật', amount: '2 tbsp' },
      { name: 'Nước mắm', amount: '1 tbsp' },
    ],
    instructions: [
      'Cắt tất cả rau thành từng miếng',
      'Làm nóng wok hoặc chảo',
      'Phi thơm tỏi và ớt',
      'Thêm hành tây, khuấy đều 5 phút',
      'Nêm gia vị với nước mắm',
    ],
  },
  {
    id: 4,
    name: 'Tomato & Garlic Sauce',
    emoji: '🍅',
    time: '10 min',
    difficulty: 'Easy',
    servings: 4,
    rating: 5,
    matchLevel: 'High match',
    ingredients: [
      { name: 'Cà chua', amount: '600g' },
      { name: 'Tỏi', amount: '5 cloves' },
      { name: 'Chanh', amount: '1 piece' },
      { name: 'Dầu olive', amount: '4 tbsp' },
      { name: 'Muối', amount: 'to taste' },
    ],
    instructions: [
      'Xay mịn cà chua hoặc dùng cà chua đóng hộp',
      'Phi thơm tỏi trong dầu olive',
      'Thêm cà chua, nấu 8 phút',
      'Thêm nước chanh',
      'Nêm gia vị và dùng ngay hoặc để nguội',
    ],
  },
]
